# Generated by Django 3.0.4 on 2020-04-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Баннер')),
                ('type', models.CharField(choices=[('carousel', 'Carousel'), ('sponsor', 'Sponsor'), ('partner', 'Partner'), ('na', 'N/A')], default='na', max_length=10, verbose_name='Тип баннера')),
                ('status', models.CharField(choices=[('on', 'On'), ('off', 'Off')], default='off', max_length=3, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннера',
                'ordering': ('-created',),
            },
        ),
    ]
