# Generated by Django 3.0.4 on 2020-04-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_active',
            field=models.IntegerField(default=0, verbose_name='Active'),
        ),
    ]
