# Generated by Django 3.0.4 on 2020-04-22 13:13

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Краткое описание')),
                ('eventDate', models.DateField(default=django.utils.timezone.now, verbose_name='Дата события')),
                ('city', models.CharField(blank=True, max_length=200, null=True, verbose_name='Город')),
                ('placement', models.CharField(blank=True, max_length=200, null=True, verbose_name='Место проведения')),
                ('eventTime', models.TimeField(default=django.utils.timezone.now, verbose_name='Время Начала')),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish', verbose_name='Ссылка')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Баннер')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст статьи')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('situation', models.FileField(blank=True, null=True, upload_to='uploads/files/', verbose_name='Файл')),
                ('type', models.CharField(choices=[('news', 'News'), ('event', 'Event')], default='event', max_length=10, verbose_name='Тип события')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, verbose_name='Статус публикации')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='posted', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ('-publish',),
            },
        ),
    ]
