# Generated by Django 3.0.4 on 2020-03-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200314_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('news', 'News'), ('event', 'Event')], default='event', max_length=10),
        ),
    ]
