# Generated by Django 3.0.4 on 2020-03-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='situation',
            field=models.FileField(null=True, upload_to='uploads/files/', verbose_name='Файл'),
        ),
    ]
