# Generated by Django 3.0.4 on 2020-04-23 14:06

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('description', models.TextField(max_length=1024, verbose_name='Описание')),
                ('thumb', imagekit.models.fields.ProcessedImageField(upload_to='videoalbums', verbose_name='Обложка')),
                ('tags', models.CharField(max_length=250, verbose_name='Теги')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимый')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Видеоальбом',
                'verbose_name_plural': 'Видеоальбомы',
                'ordering': ('-modified',),
            },
        ),
        migrations.CreateModel(
            name='AlbumVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('description', models.TextField(max_length=1024, verbose_name='Описание')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('tags', models.CharField(max_length=250, verbose_name='Теги')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимый')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('slug', models.SlugField(unique=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videogallery.Album', verbose_name='Альбом')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
                'ordering': ('-created',),
            },
        ),
    ]
