# Generated by Django 3.0.4 on 2020-04-22 20:15

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('description', models.TextField(max_length=1024, verbose_name='Описание')),
                ('thumb', imagekit.models.fields.ProcessedImageField(upload_to='albums', verbose_name='Обложка')),
                ('tags', models.CharField(max_length=250, verbose_name='Теги')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимый')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Фотоальбом',
                'verbose_name_plural': 'Фотоальбомы',
                'ordering': ('-modified',),
            },
        ),
        migrations.CreateModel(
            name='AlbumImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='albums', verbose_name='Изображение')),
                ('image_300', imagekit.models.fields.ProcessedImageField(upload_to='albums', verbose_name='Фото 300')),
                ('image_100', imagekit.models.fields.ProcessedImageField(upload_to='albums', verbose_name='Фото 100')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('width', models.IntegerField(default=0, verbose_name='Ширина')),
                ('height', models.IntegerField(default=0, verbose_name='Высота')),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, max_length=70)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photogallery.Album', verbose_name='Альбом')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'ordering': ('-created',),
            },
        ),
    ]
